Create file, first lesson
Resires/tietopythontraining-basic pull request #2
Opened 2019-09-19 08:48 UTC by Resires

Task list:

Snakify / Lesson 1 / Problems (all 6)
https://snakify.org/lessons/print_input_numbers/problems/

Snakify / Lesson 2 / Problems (first 9, skip "Clock face - 2")
https://snakify.org/lessons/integer_float_numbers/problems/

2019-09-21 19:12 UTC, jedzej requested changes

2019-09-21 19:12 UTC, jedzej commented on students/uss_tomasz/lesson_01_basics/nowy.py
> +print("Desks needed = ", ceil(a / 2) + ceil(b / 2) + ceil(c / 2))
it's fine, you could also use list for better scalability:
```
students_counts = [
  int(input()),
  int(input()),
  int(input()),
]
sum([ceil(count / 2) for count in students_counts])
```

2019-09-21 19:12 UTC, jedzej commented on students/uss_tomasz/lesson_01_basics/nowy.py
> +sum = variable % 10
sum is a built-in function, rename this variable not to shadow the built-in
```
> sum
<built-in function sum>
```

2019-09-21 19:12 UTC, jedzej commented on students/uss_tomasz/lesson_01_basics/nowy.py
> +variable = int(input("Input variable = "))
find a meaningful names for the variables

2019-09-21 19:12 UTC, jedzej commented on students/uss_tomasz/lesson_01_basics/nowy.py
> +baseLenght = float(input("Length of triangle base = "))
read PEP8 guidelines regarding variable names and adapt the code accordingly
https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

2019-09-27 16:45 UTC, jedzej approved these changes
keep up good work 🔥

2019-09-28 16:15 UTC, Resires commented
Modification finished

2019-09-28 16:18 UTC, merged